version: '3'
services:
  sync:
    image: image_app
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/app_name
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs