version: '3'
services:
  api:
    image: image_app
    ports:
      - "8000:8000"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/app_name
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs